// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoLotto/ent/schema"
	"autoLotto/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescTicketCount is the schema descriptor for ticket_count field.
	userDescTicketCount := userFields[2].Descriptor()
	// user.DefaultTicketCount holds the default value on creation for the ticket_count field.
	user.DefaultTicketCount = userDescTicketCount.Default.(int)
	// userDescWeeklyPurchase is the schema descriptor for weekly_purchase field.
	userDescWeeklyPurchase := userFields[3].Descriptor()
	// user.DefaultWeeklyPurchase holds the default value on creation for the weekly_purchase field.
	user.DefaultWeeklyPurchase = userDescWeeklyPurchase.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
