// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"bg-white p-8 rounded-lg shadow-lg w-full max-w-sm\"><h2 class=\"text-2xl font-semibold text-center mb-6\">로또 자동구매</h2><form id=\"loginForm\" action=\"/\" method=\"POST\" class=\"space-y-4\" onsubmit=\"this.querySelector(&#39;button&#39;).disabled = true;\"><div><label for=\"id\" class=\"block text-gray-700 text-sm font-medium mb-2\">동행복권 아이디</label> <input type=\"text\" id=\"id\" name=\"id\" required class=\"w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500\"></div><div><label for=\"password\" class=\"block text-gray-700 text-sm font-medium mb-2\">동행복권 비밀번호</label> <input type=\"password\" id=\"password\" name=\"password\" required class=\"w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500\"></div><button type=\"submit\" id=\"loginButton\" class=\"w-full bg-blue-500 text-white py-2 rounded-md hover:bg-blue-600 transition flex items-center justify-center\"><span class=\"spinner hidden mr-2 border-t-2 border-r-2 border-white rounded-full w-5 h-5 animate-spin\"></span> 로그인</button></form><p class=\"text-sm text-center text-gray-500 mt-4\">동행복권 아이디가 없으신가요? <a href=\"https://www.dhlottery.co.kr/loginJoin.do?method=joinFormAgree\" class=\"text-blue-500 hover:underline\">동행복권 회원가입</a></p></div><script>\n            const urlParams = new URLSearchParams(window.location.search);\n\n            // 특정 쿼리 파라미터가 있는지 확인\n            const alertMessage = urlParams.get(\"alert\");\n\n            // 값이 존재할 경우 alert 창 띄우기\n            if (alertMessage) {\n                alert(\"로그인 후 이용가능합니다.\");\n            }\n            // document.getElementById(\"loginForm\").addEventListener(\"submit\", (event) => common_submit(event, \"loginButton\", \"/\"));\n        </script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Layout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
